### ISSUE TITLE
Ausroll-Poster für Makerfaires u.Ä.

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#113]
*`Das ist eins von ein paar internen Issues, die wir schon länger auf dem Schirm hatten, die aber auch von interessierten Mitgliedern vorangebracht werden können. Ich werde die Tage noch mehr in den Issue Tracker hier posten.`*

Da wir öfter auf Makerfaires und anderen Veranstaltungen mit eigenem Stand sind wäre es gut dafür festes Marketing-Material zu haben. Hierzu würde auch ein (oder mehrere) ausrollbare Poster gut passen. Hier ein Beispiel von einem vom Hackerspace FFM:

![](https://gitlab.com/comakingspace/management/uploads/5a9ff04dc18954b4ad2b4a3dde131f07/IMGP4086__Large_.JPG)

Kurze Zusammenfassung von unseren Gedanke hierzu:
* Das Poster sollte Bilder/Motive (CAD Zeichnungen oÄ) die Interesse wecken, aber auch nicht zu voll/chaotisch wirken
 * Vielleicht kann man ein paar schöne Bilder von der Project Wall nehmen
* @LukasFreeze hatte den Vorschlag das 3D Model des Spaces drauf zu packen
*  Infos zum CoMakingSpace
  * "Offene Werkstadt in Heidelberg"
  * 24/7 access
  * Holz-, Metallverarbeitung, Elektronik, 3D Druck etc.
  * Kontaktinfo wie Adresse, Website...
* *more*

Zum Poster:

Das ausrollbare Poster wird sehr wahrscheinlich von uns dann bei Flyeralarm bestellt. Es gibt verschiedene [Größen](https://www.flyeralarm.com/de/shop/configurator/index/id/100/roll-up-classic-system-inkl-druck.html), wobei ich denke die 200x85cm sind recht sinnvoll. Der Preis liegt fertig bei um die 100€.

**Milestones**
* [ ] Person/Team finden die Interesse haben hier mirzuwirken
* [ ] Konzept über den Inhalt finden
* [ ] Bilder/Muster sammeln
* [ ] Poster entwerfen 
* [ ] @Pakue95 bestellt dann das Ausrollposter

**Comment by LukasFreeze** [comment]
Wir haben gerade nach den Making Hours noch ein bisschen designt: Wie wärs hiermit für die Zielgruppe "hätten gerne, was wir bieten, aber kennen uns noch nicht"?

![Entwurf - 'Slogans'](https://user-images.githubusercontent.com/19755883/61010484-b8003300-a376-11e9-9129-a7a6cea374d7.png)

Das zweite Poster würde ich stärker projektorientiert gestalten für die Zielgruppe "oh, das kann man selbst machen?"

Wenn da kein Feedback kommt würden wir das bis zum Bahnstadtfest (#110 ) noch bestellen, falls jemand mitgestalten möchte rücke ich auch gerne die SVG raus (ist nur hier nicht einzubinden)

**Comment by LukasFreeze** [comment]
Hier kommt Nummer zwei:

![Entwurf - 'Projekte'](https://user-images.githubusercontent.com/19755883/61148367-e39e2d00-a4de-11e9-871e-7a5e5a763d07.png)

@Pakue95 hat dann gleich im Plenum auch beide Dateien im Original, falls ihr direkt schon was rumdoktorn wollt :-)

**Comment by LukasFreeze** [comment]
Ah, noch was - die verrutschten Bilder im ersten Entwurf unten sind mittlerweile korrigiert, also haltet euch nicht damit auf ;-)

Alle gesichtsverwischten Fotos habe ich auch noch nicht-anonymisiert falls die so nicht schön sind - dann müsste das aber entweder jemand besser machen oder wir holen uns die Zustimmung von sämtlichen erkennbaren Personen...

**Comment by Pakue95** [comment]
Beide wurden bestellt 👍

**Comment by LukasFreeze** [comment]
Geil, vielen Dank! Dann sind wir nächste Woche richtig schick beflaggt ;-)

**Comment by LukasFreeze** [comment]
Die Aufsteller sind da und werden am Samstag (#110 ) eingeweiht!
