### ISSUE TITLE
Tor 4 Workshopvorbereitung: Intagliodruck mit Lasercutter und 3D-gedruckter Presse

### ISSUE THREAD

**Issue by kenomaerz** [comakingspace/do-something#174]
Lukas had the excellent idea to apply the openpressproject to our workshop. I identified a process that allows us to use Plexiglas and a laser cutter to create intaglio printing plates, that can then be used to create a number of copies using the open printing press. 
The process is described here: https://www.nycresistor.com/2012/01/21/laser-cut-letterpress/

I intend to print ~ 5-10 presses (depending how long making one print takes, have to test) and make the workshop open to ~20 participants. The workshop will consist of the following steps:

**Guided section:** Total: ~4h
1. Seminar on the process (~2h): Create an example vector illustration with all participants using Inkscape
2. General Break/Lasercut the example file with the participants (20 people sequentially using the cutter). The illustration is etched into Plexiglas plates.
3. Demonstration of the intaglio process
4. Printing the plates using the presses (will probably take a few tries to get ink/paper wetness right

**Open section:**
Participants design and print new illustrations, while seminar guides assist.

**Open Discussion:**
I invited thew openpress inventor, Martin Schneider, to hold a talk on the project

**Help:**
I need as many volunteers as I can get for this project, please let me know if you can help! Date will be announced once Martin has replied

**TODO:**

- [x] Print and assemble open press
- [ ] Make test prints using scraped Plexiglas
- [ ] Make test prints using laser cutter
- [ ] Print and assemble appropriate amount of presses
- [x] Estimate material requirements
- [x] Find sponsor for colors
- [ ] Prepare seminar content

**Comment by LukasFreeze** [comment]
(auf deutsch weil wir hier deutschen Inhalt brauchen): können wir schon einen kurzen PR-Text aufsetzen, mit dem man den Workshop "Präzisionstechnik trifft Kunst" ankündigen kann, egal ob jetzt schabloniert oder gedruckt wird? Dann könnte ich mich nämlich schon um eine Anmeldeseite kümmern (hat hier aber auch noch etwas Zeit).

**Comment by ErikSchatz** [comment]
Wann findet dieser WS statt? Wird Unterstützung benötigt?

**Comment by NitramLegov** [comment]
Da der Workshop stattgefunden hat: Brauchen wir dieses Issue noch?

Aus meiner Sicht wäre hier höchstens noch cool, den Workshop und die entstandenen Ergebnisse im Wiki zu dokumentieren :)

@LukasFreeze, @kenomaerz was meint ihr?

**Comment by LukasFreeze** [comment]
Es stehen ja noch Nachholtermine aus - ob @kenomaerz dafür dieses Issue
nutzen möchte weiß er bestimmt am besten, aber die zum Thema "Upcycling"
würde ich zB erstmal noch offen lassen :-)

**Comment by NitramLegov** [comment]
Workshop hat erfolgreich stattgefunden
