### ISSUE TITLE
Redo the control panel and emergency stop

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#67]
The emergency stop button as it is installed right now only switches the power to the stepper motors and leaves the spindle on. This could cause issues in case of an emergency as the user has to manually switch off the router motor. Also the emergency stop needs to be accessible from the outside, in case someone locks themselves out of the CNC room.

The plan to fix this would be to feed a power cable to the outside of the CNC room and hook up two e-stops in series (there are post-it notes on the planned locations). In case one of them is pushed the spindle and WorkBee will turn off.

Additionally a hardware control panel would be a good addition to the router, which was basic functions mapped to hardware buttons like: Pause/Resume, Abort, Home, (Jogging)... CNCjs supports GPIO inputs with a plugin. The Pi would also be located in the control panel.

### Electrical Stuff

* 2 Emergency Stops
  * Current one + one @Pakue95 has
* Schütz capable switching load with low voltage DC (24V)
  * [Eaton Schütz 1 St. DILEM-10-G(24VDC)](https://www.voelkner.de/products/340325/Eaton-Schuetz-1-St.-DILEM-10-G-24VDC-3-Schliesser-4kW-24-V-DC-9A-mit-Hilfskontakt.html)
* 24V DC supply
  * [Hutschienen-Schaltnetzteil MEANWELL HDR-15-24, 24 V-/0,63 A](https://www.pollin.de/p/hutschienen-schaltnetzteil-meanwell-hdr-15-24-24-v-0-63-a-352111)
* Outlet for the spindle motor
  * [inside housing](https://www.pollin.de/p/schutzkontakt-din-steckdose-gelb-551120)
  * [outside housing](https://www.pollin.de/p/schutzkontakt-steckdose-550856)
* spindle start/stop
  * [turn](https://www.voelkner.de/products/259322/Eaton-TM-1-8210-EZ-Nockenschalter-10A-2-x-60-Grau-Schwarz-1St..html)
  * [push](https://www.ebay.de/itm/250V-IP54-5E4-KJD6-Schalter-Einbauschalter-Motorschalter-Hauptschalter-NotAus-/263565698696)
* cables
* "Hutschiene"
  * [2m](https://www.voelkner.de/products/90976/Phoenix-Contact-Hutprofil-Tragschiene-NS-35-7-5-ZN-gelocht-2000MM-Inhalt-2m.html?ref=43&gclid=CjwKCAjw2_LcBRBYEiwA_XVBU0LYfdlSbbrLvbKuuc4x51FBoV0wEn97wv7QjmFpUdXw2kWbuEvrBRoC-asQAvD_BwE)
* housing
  * @NitramLegov said he has one
  * For "Hutschiene"
    * [top](https://www.pollin.de/p/modulgehaeuse-oberteil-b6-460099)
    * [bottom](https://www.pollin.de/p/modulgehaeuse-unterteil-b6-460095)

## ToDo: 

- [x] Get/Buy
  - [x] Mains Cabling + 3x socket/extension
  - [x] Additional emergency stop (the one right now could be reused)
  - [x] (optional) Machine switch to avoid accidental turn on after power loss
  - [ ] control panel
    - [ ] case
    - [ ] buttons
- [x] Drill hole for cable next to the door
- [x] install cables and endstops
- [x] Design Control panel
  - [x] Buy Buttons
  - [ ] mill the control panel
  - [ ] mount control panel
- [x] set up CNCjs for button use

**Comment by Pakue95** [comment]
I started a shopping list for the electrical components:

* 2 Emergency Stops
  * Current one + one @Pakue95 has
* Schütz capable switching load with low voltage DC (24V)
  * [Eaton Schütz 1 St. DILEM-10-G(24VDC)](https://www.voelkner.de/products/340325/Eaton-Schuetz-1-St.-DILEM-10-G-24VDC-3-Schliesser-4kW-24-V-DC-9A-mit-Hilfskontakt.html)
* 24V DC supply
  * [Hutschienen-Schaltnetzteil MEANWELL HDR-15-24, 24 V-/0,63 A](https://www.pollin.de/p/hutschienen-schaltnetzteil-meanwell-hdr-15-24-24-v-0-63-a-352111)
* Outlet for the spindle motor
  * [inside housing](https://www.pollin.de/p/schutzkontakt-din-steckdose-gelb-551120)
  * [outside housing](https://www.pollin.de/p/schutzkontakt-steckdose-550856)
* spindle start/stop
  * [turn](https://www.voelkner.de/products/259322/Eaton-TM-1-8210-EZ-Nockenschalter-10A-2-x-60-Grau-Schwarz-1St..html)
  * [push](https://www.ebay.de/itm/250V-IP54-5E4-KJD6-Schalter-Einbauschalter-Motorschalter-Hauptschalter-NotAus-/263565698696)
* cables
* "Hutschiene"
  * [2m](https://www.voelkner.de/products/90976/Phoenix-Contact-Hutprofil-Tragschiene-NS-35-7-5-ZN-gelocht-2000MM-Inhalt-2m.html?ref=43&gclid=CjwKCAjw2_LcBRBYEiwA_XVBU0LYfdlSbbrLvbKuuc4x51FBoV0wEn97wv7QjmFpUdXw2kWbuEvrBRoC-asQAvD_BwE)
* housing
  * @NitramLegov said he has one
  * For "Hutschiene"
    * [top](https://www.pollin.de/p/modulgehaeuse-oberteil-b6-460099)
    * [bottom](https://www.pollin.de/p/modulgehaeuse-unterteil-b6-460095)

**Comment by Pakue95** [comment]
Here some sketches we made on how to hook everything up:

![img_1914](https://user-images.githubusercontent.com/19751734/45599530-5b99e480-b9ed-11e8-8fc4-3fa64ba5127c.jpg)
![Uploading IMG_1915.jpg…]()

**Comment by NitramLegov** [comment]
(optional) Machine switch to avoid accidental turn on after power loss

The german keyword to look for in this case seems to be "Unterspannungsauslöser".
The one proposed by Patrick can officially be used up to 4A. Since our Router consumes around 4A, I though that might be a little tight since it´s a cheap switch. Therefore, I got a Kjd20 which can handle up to 10A. It should hopefully arrive until wednesday.

**Comment by Pakue95** [comment]
@NitramLegov wants to buy some foot switches for the router table (#64) from a [ebay shop](
http://www.ebay.de/usr/second-circle?_trksid=p2047675.l2559). They also have a suitable [Schütz](https://www.ebay.de/itm/Weg-CWCA0-22-00C03S-Schutz-1-St-2-Schlieser-2-Offner-24-V-DC-10-A-Hutschiene/173484777075?hash=item28647f9e73:g:qsAAAOSwpspbe0vJ) we could use.

**Comment by NitramLegov** [comment]
I ordered a Schütz on eBay. It should arrive early next week.
Therefore, next Wednesday I will bring the earlier mentioned Machine Switch as well as the Schütz.
The rest of the stuff can be ordered on pollin I think. @Pakue95 knows more details here.

**Comment by NitramLegov** [comment]
In regards to the control panel:
I started with a basic PCB Design, which can be found [here](https://github.com/comakingspace/CommonFiles/tree/master/PCBs/CNC_Control_Panel). However, I was too stupid to find a proper rotary switch part (e.g. a SP6T) for the speed selection.

Maybe somebody who knows KiCad better than me can check the board design and possibly add the speed selection to it. After that, we could think of ordering the board (and I guess the buttons).

**Comment by Pakue95** [comment]
I think its best to just cut a hole in the PCB layout and mount a normal "[Drehschalter](https://www.ebay.de/itm/Drehschalter-Schalter-Stufenschalter-Plastik-keramische-Struktur-1-4-Pole-Rotary/281384730845?hash=item4183d640dd:m:mioqWs4JMDqxjCSdkc3cx0w)" through it and do the connections via some pin headers. How many switch positions so we need? 

E.g.:
* 0.1mm
* 1mm
* 10mm
* 50mm
* 100mm
* 200mm

**Comment by Pakue95** [comment]
The PCB design is now updated to a 100x100mm shield for the Raspi.
* [Schematic](https://github.com/comakingspace/CommonFiles/blob/master/PCBs/CNC_Control_Panel/Plot/CNC_Control_Panel_Schematic.pdf)
![3Dview](https://raw.githubusercontent.com/comakingspace/CommonFiles/master/PCBs/CNC_Control_Panel/Plot/3D_view.png)

Please have a look if the GPIO assignment makes sense. I'm not entirely sure if all the IOs can be used as button inputs.

**Comment by Johannes09** [comment]
Verdratungsplan der Not-AUS controll Box
![06 10 18 22_20 office lens](https://user-images.githubusercontent.com/22060480/46575558-9624ea80-c9b7-11e8-889a-d8862a4f3dd1.jpg)

**Comment by Johannes09** [comment]
Not-Aus Schalter sind soweit verkabelt es fehlen nur noch ein paar Klemmbrücken besorgt werden müssen

**Comment by Pakue95** [comment]
Hab mal den Verdrahtungsplan digitalisiert. @Johannes09 kannst du schauen ob das so stimmt?
https://github.com/comakingspace/CommonFiles/blob/master/Graphics/WorkBee/Verdrahtungsplan.png
![verdrahtungsplan](https://user-images.githubusercontent.com/19751734/46924520-eb9b7000-d025-11e8-926b-f6fec7fd427a.png)

**Comment by Pakue95** [comment]
Wir haben heute die neue Elektrik getestet, jedoch ist nach einer Stunde der Schütz ungewöhnlich heiß geworden (hat sich stellenweise gelb verfärbt). Es hat sich rausgestellt dass der Schütz wohl auf 24V Wechselstrom läuft und dementsprechend auf DC 24V zu heiß wird. Martin schreibt den eBay Shop an, dass die das richtige Modell zusenden.

**Comment by Pakue95** [comment]
Das PCB Panel für den Pi habe ich am Wochenende bei JLCPCB bestellt und ist mittlerweile versandt worden.

**Comment by Johannes09** [comment]
Neuer Verdatungspaln

![unbenannt](https://user-images.githubusercontent.com/22060480/47617360-b4699c00-dac6-11e8-9fa8-f857814bf4ae.png)

**Comment by Johannes09** [comment]
Der Schaltkasten ist verkabelt und funktioniert 
![whatsapp image 2018-10-28 at 02 57 12](https://user-images.githubusercontent.com/22060480/47617436-5b4e3800-dac7-11e8-8cdc-1f70b00de856.jpeg)

**Comment by NitramLegov** [comment]
Dann mal von mir ein paar Gedanken zum Thema CNCjs & Control Panel (nur zur Doku):
Wir haben ein neues repo angelegt, das den Code beinhalten soll: https://github.com/comakingspace/cncjs-pendant-raspi-gpio
Das ist ein Fork des "offiziellen" RPi-GPIO Pendants von CNCjs und kann uns als Basis dienen.
Hier muss meiner Meinung nach noch folgendes gemacht werden:
- [ ] G-Code definieren, der bei den einzelnen Buttons jeweils an die Maschine geschickt werden soll
- [ ] Funktion definieren, die den Drehschalter ausliest (nehme an, dass das einfach ein durchgehen der inputs wird)
- [ ] In der createServer Funktion die Buttons auf den G-Code mappen
- [ ] Installieren & Testen

**Comment by Pakue95** [comment]
Die Elektrik der Fräse funktioniert soweit gut und kann meiner Meinung nach freigegeben werden. Das Controlpanel ist ja nicht für die Nutzung relevant und kann später (sobald die PCBs da sind) hinzugefügt werden.

**Comment by NitramLegov** [comment]
Der Code für das ControlPanel ist jetzt größtenteils fertig und als service auf dem pi eingerichtet.
Es fehlt noch der code für den drehknopf und der code für #45

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by NitramLegov** [comment]
Control Panel ist fertig und fertig eingerichtet. Bugs werden in #204 geklärt
